server:
  port: 8080
  tomcat:
    threads:
      max: 200
    accept-count: 100 #可修改参数，最大线程数和最大队列长度
    max-connections: 1000
spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.112:3306/FD_XZ_DATABASE?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: root
  redis:
    host: 192.168.1.113
    port: 6379
  neo4j:
    uri: bolt://192.168.1.112:7687
    authentication:
      username: neo4j
  rabbitmq:
    host: 192.168.1.113
    port: 5672
    virtual-host: /tiancai
    username: xz
    password: 200074xz666
    listener:
      simple:
        prefetch: 1
    connection-timeout: 1s #连接超时时间
    template:
      retry:
        enabled: true
        initial-interval: 1s  #重试间隔时间
        multiplier: 1     #重试时间间隔倍数
        max-attempts: 2   #最大重试次数


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      alarm:
        mapper: debug
        service: info
        controller: info